/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAppRouteImport } from './routes/admin._app'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAppIndexRouteImport } from './routes/admin._app.index'
import { Route as AdminAppActivityRouteImport } from './routes/admin._app.activity'
import { Route as AdminAppAnalyticsRouteImport } from './routes/admin._app.analytics'
import { Route as AdminAppBlogRouteImport } from './routes/admin._app.blog'
import { Route as AdminAppCareersRouteImport } from './routes/admin._app.careers'
import { Route as AdminAppCategoriesRouteImport } from './routes/admin._app.categories'
import { Route as AdminAppMediaRouteImport } from './routes/admin._app.media'
import { Route as AdminAppMessagesRouteImport } from './routes/admin._app.messages'
import { Route as AdminAppProductsRouteImport } from './routes/admin._app.products'
import { Route as AdminAppSubscribersRouteImport } from './routes/admin._app.subscribers'
import { Route as AdminAppTeamRouteImport } from './routes/admin._app.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/admin/_app',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppIndexRoute = AdminAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppActivityRoute = AdminAppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppAnalyticsRoute = AdminAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppBlogRoute = AdminAppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppCareersRoute = AdminAppCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppCategoriesRoute = AdminAppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppMediaRoute = AdminAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppMessagesRoute = AdminAppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppProductsRoute = AdminAppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppSubscribersRoute = AdminAppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppTeamRoute = AdminAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAppRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/activity': typeof AdminAppActivityRoute
  '/admin/analytics': typeof AdminAppAnalyticsRoute
  '/admin/blog': typeof AdminAppBlogRoute
  '/admin/careers': typeof AdminAppCareersRoute
  '/admin/categories': typeof AdminAppCategoriesRoute
  '/admin/media': typeof AdminAppMediaRoute
  '/admin/messages': typeof AdminAppMessagesRoute
  '/admin/products': typeof AdminAppProductsRoute
  '/admin/subscribers': typeof AdminAppSubscribersRoute
  '/admin/team': typeof AdminAppTeamRoute
  '/admin/': typeof AdminAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/activity': typeof AdminAppActivityRoute
  '/admin/analytics': typeof AdminAppAnalyticsRoute
  '/admin/blog': typeof AdminAppBlogRoute
  '/admin/careers': typeof AdminAppCareersRoute
  '/admin/categories': typeof AdminAppCategoriesRoute
  '/admin/media': typeof AdminAppMediaRoute
  '/admin/messages': typeof AdminAppMessagesRoute
  '/admin/products': typeof AdminAppProductsRoute
  '/admin/subscribers': typeof AdminAppSubscribersRoute
  '/admin/team': typeof AdminAppTeamRoute
  '/admin': typeof AdminAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_app': typeof AdminAppRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/_app/activity': typeof AdminAppActivityRoute
  '/admin/_app/analytics': typeof AdminAppAnalyticsRoute
  '/admin/_app/blog': typeof AdminAppBlogRoute
  '/admin/_app/careers': typeof AdminAppCareersRoute
  '/admin/_app/categories': typeof AdminAppCategoriesRoute
  '/admin/_app/media': typeof AdminAppMediaRoute
  '/admin/_app/messages': typeof AdminAppMessagesRoute
  '/admin/_app/products': typeof AdminAppProductsRoute
  '/admin/_app/subscribers': typeof AdminAppSubscribersRoute
  '/admin/_app/team': typeof AdminAppTeamRoute
  '/admin/_app/': typeof AdminAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/careers'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/_app'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/_app/activity'
    | '/admin/_app/analytics'
    | '/admin/_app/blog'
    | '/admin/_app/careers'
    | '/admin/_app/categories'
    | '/admin/_app/media'
    | '/admin/_app/messages'
    | '/admin/_app/products'
    | '/admin/_app/subscribers'
    | '/admin/_app/team'
    | '/admin/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAppRoute: typeof AdminAppRouteWithChildren
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app': {
      id: '/admin/_app'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app/': {
      id: '/admin/_app/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAppIndexRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/activity': {
      id: '/admin/_app/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminAppActivityRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/analytics': {
      id: '/admin/_app/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAppAnalyticsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/blog': {
      id: '/admin/_app/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminAppBlogRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/careers': {
      id: '/admin/_app/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminAppCareersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/categories': {
      id: '/admin/_app/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAppCategoriesRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/media': {
      id: '/admin/_app/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAppMediaRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/messages': {
      id: '/admin/_app/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAppMessagesRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/products': {
      id: '/admin/_app/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAppProductsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/subscribers': {
      id: '/admin/_app/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminAppSubscribersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/team': {
      id: '/admin/_app/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAppTeamRouteImport
      parentRoute: typeof AdminAppRoute
    }
  }
}

interface AdminAppRouteChildren {
  AdminAppActivityRoute: typeof AdminAppActivityRoute
  AdminAppAnalyticsRoute: typeof AdminAppAnalyticsRoute
  AdminAppBlogRoute: typeof AdminAppBlogRoute
  AdminAppCareersRoute: typeof AdminAppCareersRoute
  AdminAppCategoriesRoute: typeof AdminAppCategoriesRoute
  AdminAppMediaRoute: typeof AdminAppMediaRoute
  AdminAppMessagesRoute: typeof AdminAppMessagesRoute
  AdminAppProductsRoute: typeof AdminAppProductsRoute
  AdminAppSubscribersRoute: typeof AdminAppSubscribersRoute
  AdminAppTeamRoute: typeof AdminAppTeamRoute
  AdminAppIndexRoute: typeof AdminAppIndexRoute
}

const AdminAppRouteChildren: AdminAppRouteChildren = {
  AdminAppActivityRoute: AdminAppActivityRoute,
  AdminAppAnalyticsRoute: AdminAppAnalyticsRoute,
  AdminAppBlogRoute: AdminAppBlogRoute,
  AdminAppCareersRoute: AdminAppCareersRoute,
  AdminAppCategoriesRoute: AdminAppCategoriesRoute,
  AdminAppMediaRoute: AdminAppMediaRoute,
  AdminAppMessagesRoute: AdminAppMessagesRoute,
  AdminAppProductsRoute: AdminAppProductsRoute,
  AdminAppSubscribersRoute: AdminAppSubscribersRoute,
  AdminAppTeamRoute: AdminAppTeamRoute,
  AdminAppIndexRoute: AdminAppIndexRoute,
}

const AdminAppRouteWithChildren = AdminAppRoute._addFileChildren(
  AdminAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAppRoute: AdminAppRouteWithChildren,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
